// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXVs-oRZpP1kO2KQcLnhENRTbTsa-SmUI',
    appId: '1:132611500639:web:841aff2a2bf92203ba09ea',
    messagingSenderId: '132611500639',
    projectId: 'trackmoney-e2bd1',
    authDomain: 'trackmoney-e2bd1.firebaseapp.com',
    storageBucket: 'trackmoney-e2bd1.firebasestorage.app',
    measurementId: 'G-DGPPZ25Q8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1WvfhgFIF6E7vdzxaVE7iFzJEHte4SsU',
    appId: '1:132611500639:android:84f83e0b33b3149dba09ea',
    messagingSenderId: '132611500639',
    projectId: 'trackmoney-e2bd1',
    storageBucket: 'trackmoney-e2bd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIhm02W4nzcFfdiM6Gbr67Xx4SWLslQiQ',
    appId: '1:132611500639:ios:fe55e13cf0637cabba09ea',
    messagingSenderId: '132611500639',
    projectId: 'trackmoney-e2bd1',
    storageBucket: 'trackmoney-e2bd1.firebasestorage.app',
    iosBundleId: 'com.example.trackmoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIhm02W4nzcFfdiM6Gbr67Xx4SWLslQiQ',
    appId: '1:132611500639:ios:fe55e13cf0637cabba09ea',
    messagingSenderId: '132611500639',
    projectId: 'trackmoney-e2bd1',
    storageBucket: 'trackmoney-e2bd1.firebasestorage.app',
    iosBundleId: 'com.example.trackmoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXVs-oRZpP1kO2KQcLnhENRTbTsa-SmUI',
    appId: '1:132611500639:web:ce11c7d314253da4ba09ea',
    messagingSenderId: '132611500639',
    projectId: 'trackmoney-e2bd1',
    authDomain: 'trackmoney-e2bd1.firebaseapp.com',
    storageBucket: 'trackmoney-e2bd1.firebasestorage.app',
    measurementId: 'G-BG0Q7W6QD9',
  );
}
